spring:
  application:
    name: microervice-discovery-eureka-ha
  security:
    user:
      name: hong
      password: root
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8761/eureka/  # 前面加不加 xx:yy (无论是啥,好像都没有影响)
    register-with-eureka: false
    fetch-registry: false
server:
  port: 8761
#
#---
#spring:
#  profiles: peer1
#server:
#  port: 8761
#eureka:
#  instance:
#    hostname: peer1
#---
#spring:
#  profiles: peer2
#server:
#  port: 8762
#eureka:
#  instance:
#    hostname: peer2