management:
  endpoints:
    web:
      exposure:
        include: '*'
        # 2.x只暴露很有限的端点,需要手动配置暴露,才能使用refresh端点.
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true


