server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/itmuch/spring-cloud-config-repo
          # https://github.com/Hongscar/microService
          search-paths: config-repo
          username:
          password:
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
