#encrypt:
##  key: foo  # 对称加密密钥
#  key-store:
#    location: classpath:server.jks    # jks文件的路径
#    password: letmein                 # storepass
#    alias: mytestkey                  # alias
##    secret: changeme                 # keypass

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    appname: configserver

