server:
  port: 8010
info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    version: 1.0.0
    test: test
    java:
      source: @java.version@
      target: @java.version@
manager:
  endpoints:
    web:
      exposure:
        include: all
    health:
      show-details: always
    shutdown:
      enabled: true
feign:
  client:
    config:
      feignName:          # 改成 default 就是全局配置
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
        # errorDecoder: com.xxxx
        # retryer: com.xxx
        #requestInterceptors:
        #  - com.xxx
        #  - com.xxx
        decode404: false
#spring:
#  cloud:
#    service-registry:
#      auto-registration:
#        enabled: false   确实可以禁止服务注册到 Eureka