server:
  port: 8010
info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    version: 1.0.0
    test: test
    java:
      source: @java.version@
      target: @java.version@
manager:
  endpoints:
    web:
      exposure:
        include: all
    health:
      show-details: always
    shutdown:
      enabled: true
#spring:
#  cloud:
#    service-registry:
#      auto-registration:
#        enabled: false   确实可以禁止服务注册到 Eureka