server:
  port: 8050
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: microservice-file-upload
  servlet:
    multipart:
      max-file-size: 200MB      # default 1M
      max-request-size: 300MB   # default 10M

#hystix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 60000
#ribbon:
#  ConnectTimeout: 30000
#  ReadTimeout: 60000

